attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  stock_id:
    ACU: 0
    AE: 1
    AEF: 2
    AIM: 3
    AIRI: 4
    AMBO: 5
    AMS: 6
    APT: 7
    AREN: 8
    ARMN: 9
    ARMP: 10
    ASM: 11
    ATNM: 12
    AUMN: 13
    AWX: 14
    BATL: 15
    BCV: 16
    BDL: 17
    BGI: 18
    BHB: 19
    BKTI: 20
    BMTX: 21
    BRBS: 22
    BRN: 23
    BTG: 24
    BTTR: 25
    CANF: 26
    CATX: 27
    CCEL: 28
    CET: 29
    CEV: 30
    CIK: 31
    CIX: 32
    CKX: 33
    CLM: 34
    CMCL: 35
    CMT: 36
    COE: 37
    COHN: 38
    CPHI: 39
    CRF: 40
    CTGO: 41
    CVM: 42
    CVR: 43
    CVU: 44
    CYBN: 45
    DHY: 46
    DIT: 47
    DMF: 48
    DNN: 49
    DSS: 50
    EAD: 51
    ECF: 52
    EFSH: 53
    EIM: 54
    ELA: 55
    ELLO: 56
    ELMD: 57
    EMX: 58
    ENSV: 59
    ENX: 60
    EP: 61
    EPM: 62
    EQX: 63
    ERH: 64
    ESP: 65
    EVBN: 66
    EVI: 67
    EVM: 68
    EVV: 69
    FAX: 70
    FCO: 71
embedding_paddings: []
embedding_sizes:
  stock_id: !!python/tuple
  - 72
  - 18
hidden_continuous_size: 4
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.05
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 60
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    ZPwZQA==
  max_length: null
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AQAAYE/Y+j8=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- stock_id
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
weight_decay: 0.0
x_categoricals:
- stock_id
x_reals:
- encoder_length
- relative_time_idx
- High
- Low
- Close
- Volume
