attention_head_size: 16
categorical_groups: {}
causal_attention: true
dropout: 0.05
embedding_labels:
  day_of_week:
    '0': 0
    '1': 1
    '2': 2
    '3': 3
    '4': 4
    '5': 5
    '6': 6
  stock_id:
    TSLA: 0
embedding_paddings: []
embedding_sizes:
  day_of_week: !!python/tuple
  - 7
  - 8
  stock_id: !!python/tuple
  - 1
  - 64
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 256
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 3
max_encoder_length: 60
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 5
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    dYaIQA==
  max_length: null
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AQAAgMdH8z8=
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- stock_id
static_reals:
- DividendRate
- MarketCap
- PERatio
- PriceToBook
- DebtToEquity
- ShortRatio
- AnalystTargetPrice
- encoder_length
time_varying_categoricals_decoder:
- day_of_week
time_varying_categoricals_encoder:
- day_of_week
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
- OBV
- RealizedVol
- sentiment
- wsb_sentiment
weight_decay: 0.0
x_categoricals:
- stock_id
- day_of_week
x_reals:
- DividendRate
- MarketCap
- PERatio
- PriceToBook
- DebtToEquity
- ShortRatio
- AnalystTargetPrice
- encoder_length
- relative_time_idx
- High
- Low
- Close
- Volume
- OBV
- RealizedVol
- sentiment
- wsb_sentiment
