attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  stock_id:
    ACU: 0
    AE: 1
    AEF: 2
    AIM: 3
    AIRI: 4
    AMBO: 5
    AMS: 6
    APT: 7
    AREN: 8
    ARMN: 9
    ARMP: 10
    ASM: 11
    ATNM: 12
    AUMN: 13
    AWX: 14
    BATL: 15
    BCV: 16
    BDL: 17
    BGI: 18
    BHB: 19
    BKTI: 20
    BMTX: 21
    BRBS: 22
    BRN: 23
    BTG: 24
    BTTR: 25
    CANF: 26
    CATX: 27
    CCEL: 28
    CET: 29
    CEV: 30
    CIK: 31
    CIX: 32
    CKX: 33
    CLM: 34
    CMCL: 35
    CMT: 36
    COE: 37
    COHN: 38
    CPHI: 39
    CRF: 40
    CTGO: 41
    CVM: 42
    CVR: 43
    CVU: 44
    CYBN: 45
    DHY: 46
    DIT: 47
    DMF: 48
    DNN: 49
    DSS: 50
    EAD: 51
    ECF: 52
    EFSH: 53
    EIM: 54
    ELA: 55
    ELLO: 56
    ELMD: 57
    EMX: 58
    ENSV: 59
    ENX: 60
    EP: 61
    EPM: 62
    EQX: 63
    ERH: 64
    ESP: 65
    EVBN: 66
    EVI: 67
    EVM: 68
    EVV: 69
    FAX: 70
    FCO: 71
    FRD: 72
    FSI: 73
    FSP: 74
    FTF: 75
    FURY: 76
    GAU: 77
    GBR: 78
    GENC: 79
    GGN: 80
    GLDG: 81
    GLO: 82
    GLQ: 83
    GLU: 84
    GLV: 85
    GORO: 86
    GPUS: 87
    GRF: 88
    GSAT: 89
    GTE: 90
    HNW: 91
    HUSA: 92
    IAF: 93
    IBIO: 94
    IDR: 95
    IGC: 96
    IHT: 97
    IMO: 98
    INDO: 99
    INFU: 100
    INLX: 101
    INTT: 102
    INUV: 103
    IOR: 104
    ISDR: 105
    ITP: 106
    JOB: 107
    KNW: 108
    KULR: 109
    LCTX: 110
    LEU: 111
    LGL: 112
    LODE: 113
    LXFR: 114
    MAG: 115
    MHH: 116
    MI: 117
    MLSS: 118
    MPU: 119
    MSN: 120
    MTA: 121
    MTNB: 122
    MXC: 123
    MYND: 124
    MYO: 125
    NAK: 126
    NBH: 127
    NBY: 128
    NEN: 129
    NEWP: 130
    NG: 131
    NGD: 132
    NHC: 133
    NHS: 134
    NML: 135
    NNVC: 136
    NRO: 137
    NTIP: 138
    OBE: 139
    OGEN: 140
    OPTT: 141
    ORLA: 142
    PED: 143
    PHGE: 144
    PLAG: 145
    PLG: 146
    PLX: 147
    PRK: 148
    PTN: 149
    PW: 150
    PZG: 151
    RCG: 152
    REI: 153
    REPX: 154
    RHE: 155
    RLGT: 156
    RVP: 157
    SACC: 158
    SACH: 159
    SBEV: 160
    SCPX: 161
    SEB: 162
    SENS: 163
    SER: 164
    SIF: 165
    SILV: 166
    SIM: 167
    SLI: 168
    SSY: 169
    STXS: 170
    SVM: 171
    SVT: 172
    TGB: 173
    THM: 174
    TMP: 175
    TMQ: 176
    TOON: 177
    TOPS: 178
    TOVX: 179
    TRT: 180
    TRX: 181
    UAMY: 182
    UAVS: 183
    UEC: 184
    URG: 185
    USAS: 186
    UTG: 187
    UUU: 188
    UUUU: 189
    VFL: 190
    VGZ: 191
    VKI: 192
    VNRX: 193
    VTAK: 194
    WRN: 195
    WWR: 196
    WYY: 197
    XPL: 198
    XTNT: 199
    YCBD: 200
    ZDGE: 201
    ZOM: 202
embedding_paddings: []
embedding_sizes:
  stock_id: !!python/tuple
  - 203
  - 31
hidden_continuous_size: 4
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.05
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 60
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    B1MQQA==
  max_length: null
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAANqdBEA=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- stock_id
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
weight_decay: 0.0
x_categoricals:
- stock_id
x_reals:
- encoder_length
- relative_time_idx
- High
- Low
- Close
- Volume
