attention_head_size: 4
categorical_groups: {}
causal_attention: true
dropout: 0.1
embedding_labels:
  stock_id:
    AAPL: 0
    AMD: 1
    BTU: 2
    CVNA: 3
    META: 4
    NVDA: 5
    TSLA: 6
    X: 7
embedding_paddings: []
embedding_sizes:
  stock_id: !!python/tuple
  - 8
  - 5
hidden_continuous_size: 4
hidden_continuous_sizes: {}
hidden_size: 32
learning_rate: 0.05
log_gradient_flow: false
log_interval: -1
log_val_interval: null
lstm_layers: 1
max_encoder_length: 60
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 50
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f4
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    xsg/QA==
  max_length: null
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AQAAAHng9D8=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- stock_id
static_reals:
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
weight_decay: 0.0
x_categoricals:
- stock_id
x_reals:
- encoder_length
- relative_time_idx
- High
- Low
- Close
- Volume
