attention_head_size: 8
categorical_groups: {}
causal_attention: true
dropout: 0.05
embedding_labels:
  stock_id:
    XOM: 0
embedding_paddings: []
embedding_sizes:
  stock_id: !!python/tuple
  - 1
  - 1
hidden_continuous_size: 16
hidden_continuous_sizes: {}
hidden_size: 128
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
lstm_layers: 3
max_encoder_length: 60
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 3
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDQAAADIwMjQ4NjYwNzUwMDhxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMDI0
      ODY2MDc1MDA4cQFhLgEAAAAAAAAAU4CHQA==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_length: null
  method: standard
  scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDQAAADIwMjQ4NjYwNzE1NTJxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWA0AAAAyMDI0
      ODY2MDcxNTUycQFhLgEAAAAAAAAA2jGKPA==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  transformation: relu
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
reduce_on_plateau_reduction: 2.0
share_single_variable_networks: false
static_categoricals:
- stock_id
static_reals:
- DividendRate
- MarketCap
- PERatio
- PriceToBook
- DebtToEquity
- ShortRatio
- AnalystTargetPrice
- encoder_length
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
- High
- Low
- Close
- Volume
- OBV
weight_decay: 0.0
x_categoricals:
- stock_id
x_reals:
- DividendRate
- MarketCap
- PERatio
- PriceToBook
- DebtToEquity
- ShortRatio
- AnalystTargetPrice
- encoder_length
- relative_time_idx
- High
- Low
- Close
- Volume
- OBV
